Web/Models/ErrorViewModel.cs
namespace Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/Models/IndexViewModel.cs
namespace Web.Models
{
    public class DeseignPatternsViewModel
    {
        public DeseignPatternsViewModel(string name) 
        {
            Name = name;
        }

        public string Name { get; set; }
    }
}

Web/Controllers/AboutMeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Web.Models;

namespace RockPaperCode.Controllers
{
    public class AboutMeController : Controller
    {
        private readonly ILogger<AboutMeController> _logger;

        public AboutMeController(ILogger<AboutMeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/Controllers/CSharpCodeSamplesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System.Diagnostics;
using Web.Models;

namespace RockPaperCode.Controllers
{
    public class CSharpCodeSamplesController : Controller
    {
        private readonly ILogger<CSharpCodeSamplesController> _logger;

        public CSharpCodeSamplesController(ILogger<CSharpCodeSamplesController> logger)
        {
            _logger = logger;
        }

        public IActionResult CSharp()
        {
            return View();
        }

        public IActionResult CodeSample(string codeSample)
        {
            return PartialView(codeSample);
        }
    }
}

Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Web.Models;

namespace RockPaperCode.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Controllers/HtmlCodeSamplesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System.Diagnostics;
using Web.Models;

namespace RockPaperCode.Controllers
{
    public class HtmlCodeSamplesController : Controller
    {
        private readonly ILogger<HtmlCodeSamplesController> _logger;

        public HtmlCodeSamplesController(ILogger<HtmlCodeSamplesController> logger)
        {
            _logger = logger;
        }

        public IActionResult Html()
        {
            return View();
        }

        public IActionResult CodeSample(string codeSample) 
        { 
            return PartialView(codeSample); 
        }
    }
}

Web/Controllers/JavaScriptCodeSamplesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System.Diagnostics;
using Web.Models;

namespace RockPaperCode.Controllers
{
    public class JavaScriptCodeSamplesController : Controller
    {
        private readonly ILogger<JavaScriptCodeSamplesController> _logger;

        public JavaScriptCodeSamplesController(ILogger<JavaScriptCodeSamplesController> logger)
        {
            _logger = logger;
        }

        public IActionResult JavaScript()
        {
            return View();
        }

        public IActionResult CodeSample(string codeSample)
        {
            return PartialView(codeSample);
        }
    }
}

Web/Views/AboutMe/Index.cshtml
@{
    ViewData["Title"] = "About Me";
}

<div class="text-center">
    @* <iframe src="file_name.pdf" style="width: 100%;height: 100%;border: none;"></iframe> *@
</div>

Web/Views/CSharpCodeSamples/CSharp.cshtml
@{
    ViewData["Title"] = "C# Code Samples";
}
@section Scripts
{
    <script>
        // HTML Code Sample JS Code
        $(document).ready(function () {
            $("#cSharpSampleDropdown").on("change",
                function (e) {
                    var codeSample = $("#cSharpSampleDropdown").val();
                    $("#cSharpCodeExamplePartialRender").load("/CodeSamples/cSharpCodeSample", { codeSample: codeSample });
                });
        });
    </script>
}

<div class="row text-center">
    <h1>C# Code Samples</h1>
</div>

<br />

<!--Code Sample Selector-->
<div class="row">
    <div class="col-3">
        <select id="cSharpSampleDropdown" class="form-select" aria-label="Default select example">
            <option value="_PartialCSharpIndex" selected></option>
            <option value="_PartialGoFSingleton">Singleton</option>
            <option value="_PartialGoFPrototype">Prototype</option>
            <option value="_PartialGoFBuilder">Builder</option>
            <option value="_PartialGoFFactory">Factory</option>
        </select>
    </div>
</div>

<br />
<hr />
<br />
<br />

<!--Partial Render Window-->
<div class="container-fluid" id="cSharpCodeExamplePartialRender">
    <br />
    <br />
    <br />
    <br />
    <br />
</div>

Web/Views/CodeSamples/Html.cshtml
@{
    ViewData["Title"] = "HTML Code Samples";
}
@section Scripts
{
    <script>
        // HTML Code Sample JS Code
        $(document).ready(function () {
            $("#htmlSampleDropdown").on("change",
                function (e) {
                    var codeSample = $("#htmlSampleDropdown").val();
                    $("#htmlCodeExamplePartialRender").load("/CodeSamples/HtmlCodeSample", { codeSample: codeSample });
                });
        });
    </script>
}

<div class="row text-center">
    <h1>HTML Code Samples</h1>
</div>

<br />

<!--Code Sample Selector-->
<div class="row">
    <div class="col-3">
        <select id="htmlSampleDropdown" class="form-select" aria-label="Default select example">
            <option value="_PartialHtmlIndex" selected></option>
            <option value="_PartialHtmlAccordion">Accordion</option>
            <option value="_PartialHtmlCards">Cards</option>
            <option value="_PartialHtmlCarousel">Carousel</option>
            <option value="_PartialHtmlForms">Forms</option>
            <option value="_PartialHtmlLists">Lists</option>
            <option value="_PartialHtmlModals">Modals</option>
            <option value="_PartialHtmlTables">Tables</option>
        </select>
    </div>    
</div>

<br />
<hr />
<br />
<br />

<!--Partial Render Window-->
<div class="container-fluid" id="htmlCodeExamplePartialRender">
    <br /> 
    <br /> 
    <br /> 
    <br /> 
    <br />
</div>

Web/Views/CodeSamples/_PartialHtmlLists.cshtml
@section Scripts
{
    <script>
        // Partial HTML Lists Scripts
    </script>
}

Lists

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Rock-Paper-Code!</h1>
    <br/><br/>
    <div class="row">
        <div class="col">
            <h1>Purpose</h1>
            <p>Sandbox for testing various <code>code</code> examples!</p>
        </div>
        <div class="col">
            <h1>Feedback</h1>
            <p>All feedback should be directed towards the <a href="https://github.com/markrissinger/RockPaperCode">GIT repository</a>.</p>
        </div>
    </div>
</div>

Web/Views/HtmlCodeSamples/Html.cshtml
@{
    ViewData["Title"] = "HTML Code Samples";
}
@section Scripts
{
    <script>
        // HTML Code Sample JS Code
        $(document).ready(function () {
            $("#htmlSampleDropdown").on("change",
                function (e) {
                    var codeSample = $("#htmlSampleDropdown").val();
                    $("#htmlCodeExamplePartialRender").load("/HtmlCodeSamples/CodeSample", { codeSample: codeSample });
                });
        });
    </script>
}

<div class="row text-center">
    <h1>HTML Code Samples</h1>
</div>

<br />

<!--Code Sample Selector-->
<div class="row">
    <div class="col-3">
        <select id="htmlSampleDropdown" class="form-select" aria-label="Default select example">
            <option value="_PartialHtmlIndex" selected></option>
            <option value="_PartialHtmlAccordion">Accordion</option>
            <option value="_PartialHtmlCards">Cards</option>
            <option value="_PartialHtmlCarousel">Carousel</option>
            <option value="_PartialHtmlForms">Forms</option>
            <option value="_PartialHtmlLists">Lists</option>
            <option value="_PartialHtmlModals">Modals</option>
            <option value="_PartialHtmlTables">Tables</option>
        </select>
    </div>    
</div>

<br />
<hr />
<br />
<br />

<!--Partial Render Window-->
<div class="container-fluid" id="htmlCodeExamplePartialRender">
    <br /> 
    <br /> 
    <br /> 
    <br /> 
    <br />
</div>

Web/Views/HtmlCodeSamples/_PartialHtmlAccordion.cshtml
@section Scripts
{
    <script>
        // Partial HTML Lists Accordion
    </script>
}
@{
    var sampleObjectCount = 10;
}

<div class="row">
    <div class="col-5">     
        <div class="row">
            <h3>Standard Accordion</h3>
        </div>
        <br />
        <div class="row">
            <div class="accordion" id="accordionStandard">
                @{
                    for (var i = 0; i < sampleObjectCount; i++)
                    {
                        <div class="accordion-item">
                            <h2 class="accordion-header">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStandard-collapse@(i)"                                 aria-expanded="false" aria-controls="panelsStandard-collapse@(i)">
                                    Object #@(i).
                                </button>
                            </h2>
                            <div id="panelsStandard-collapse@(i)" class="accordion-collapse collapse" data-bs-parent="#accordionStandard">
                                <div class="accordion-body">
                                    Object body.
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>        
    </div>
    <div class="col-5 offset-2">
        <div class="row">
            <h3>Open Accordion</h3>
        </div>
        <br />
        <div class="row">
            <div class="accordion" id="accordionStayOpen">
                @{
                    for (var i = 0; i < sampleObjectCount; i++)
                    {
                        <div class="accordion-item">
                            <h2 class="accordion-header">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse@(i)" aria-expanded="false" aria-controls="panelsStayOpen-collapse@(i)">
                                    Object #@(i)
                                </button>
                            </h2>
                            <div id="panelsStayOpen-collapse@(i)" class="accordion-collapse collapse">
                                <div class="accordion-body">
                                    Object body.
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
        
    </div>
</div>

Web/Views/HtmlCodeSamples/_PartialHtmlCards.cshtml
@section Scripts
{
    <script>
        // Partial HTML Lists Scripts
    </script>
}

<div class="row">
    <div class="card text-center">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link active" href="#">Active</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
    </div>
</div>

Web/Views/HtmlCodeSamples/_PartialHtmlCarousel.cshtml
@section Scripts
{
    <script>
        // Partial HTML Lists Scripts
    </script>
}

<h3>Basic List</h3>
<br />
<div class="row">
    <div class="col-6 offset-3">
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 1</li>
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 2</li>
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 3</li>
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 4</li>
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 5</li>
        </ul>
    </div>
</div>

<br /><hr /><br />


<h3>Custom List</h3>
<br />
<div class="row">
    <div class="col-8 offset-2">
        <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action" aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Object 1</h5>
                    <small>Note</small>
                </div>
                <p class="mb-1">Description</p>
                <small>Details</small>
            </a>
            <a href="#" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Object 2</h5>
                    <small>Note</small>
                </div>
                <p class="mb-1">Description</p>
                <small>Details</small>
            </a>
            <a href="#" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Object 3</h5>
                    <small>Note</small>
                </div>
                <p class="mb-1">Description</p>
                <small>Details</small>
            </a>
        </div>
    </div>
</div>

<br />
<hr />
<br />

Web/Views/HtmlCodeSamples/_PartialHtmlForms.cshtml
@section Scripts
{
    <script>
        // Partial HTML Lists Scripts
    </script>
}

Forms

Web/Views/HtmlCodeSamples/_PartialHtmlIndex.cshtml
@section Scripts
{
    <script>
        // Partial HTML Index Scripts
    </script>
}

Web/Views/HtmlCodeSamples/_PartialHtmlLists.cshtml
@section Scripts
{
    <script>
        // Partial HTML Lists Scripts
    </script>
}

<h3>Basic List</h3>
<br />
<div class="row">
    <div class="col-6 offset-3">
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 1</li>
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 2</li>
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 3</li>
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 4</li>
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 5</li>
        </ul>
    </div>
</div>

<br /><hr /><br />


<h3>Custom List</h3>
<br />
<div class="row">
    <div class="col-8 offset-2">
        <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action" aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Object 1</h5>
                    <small>Note</small>
                </div>
                <p class="mb-1">Description</p>
                <small>Details</small>
            </a>
            <a href="#" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Object 2</h5>
                    <small>Note</small>
                </div>
                <p class="mb-1">Description</p>
                <small>Details</small>
            </a>
            <a href="#" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Object 3</h5>
                    <small>Note</small>
                </div>
                <p class="mb-1">Description</p>
                <small>Details</small>
            </a>
        </div>
    </div>
</div>

<br />
<hr />
<br />

Web/Views/HtmlCodeSamples/_PartialHtmlModals.cshtml
@section Scripts
{
    <script>
        // Partial HTML Lists Scripts
    </script>
}

<h3>Basic List</h3>
<br />
<div class="row">
    <div class="col-6 offset-3">
        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 1</li>
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 2</li>
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 3</li>
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 4</li>
            <li class="list-group-item d-flex justify-content-between align-items-start">Object 5</li>
        </ul>
    </div>
</div>

<br /><hr /><br />


<h3>Custom List</h3>
<br />
<div class="row">
    <div class="col-8 offset-2">
        <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action" aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Object 1</h5>
                    <small>Note</small>
                </div>
                <p class="mb-1">Description</p>
                <small>Details</small>
            </a>
            <a href="#" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Object 2</h5>
                    <small>Note</small>
                </div>
                <p class="mb-1">Description</p>
                <small>Details</small>
            </a>
            <a href="#" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">Object 3</h5>
                    <small>Note</small>
                </div>
                <p class="mb-1">Description</p>
                <small>Details</small>
            </a>
        </div>
    </div>
</div>

<br />
<hr />
<br />

Web/Views/HtmlCodeSamples/_PartialHtmlTables.cshtml
@section Scripts
{
    <script>
        // Parital HTML Tables Scripts
    </script>
}

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th scope="col"> Row </th>
            <th scope="col"> A0 </th>
            <th scope="col"> B0 </th>
            <th scope="col"> C0 </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td scope="row"> 1 </td>
            <td> A1 </td>
            <td> B1 </td>
            <td> C1 </td>
        </tr>
        <tr>
            <td scope="row"> 2 </td>
            <td> A2 </td>
            <td> B2 </td>
            <td> C2 </td>
        </tr>
        <tr>
            <td scope="row"> 3 </td>
            <td> A3 </td>
            <td> B3 </td>
            <td> C3 </td>
        </tr>
        <tr>
            <td scope="row"> 4 </td>
            <td> A4 </td>
            <td> B4 </td>
            <td> C4 </td>
        </tr>
        <tr>
            <td scope="row"> 5 </td>
            <td> A5 </td>
            <td> B5 </td>
            <td> C5 </td>
        </tr>
    </tbody>
</table>

Web/Views/JavaScript/JavaScript.cshtml
@{
    ViewData["Title"] = "JavaScript Code Samples";
}

<div class="text-center">
    <h1 class="display-4">JavaScript Code Samples!</h1>
    <br/><br/>
    <div class="row">
    </div>
</div>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>RockPaperCode - @ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RockPaperCode.styles.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RockPaperCode</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Code Samples
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="HtmlCodeSamples" asp-action="Html">HTML & CSS</a>
                                <a class="dropdown-item disabled" asp-area="" asp-controller="JavaScriptCodeSamples" asp-action="JavaScript">JavaScript</a>
                                <a class="dropdown-item" asp-area="" asp-controller="CSharpCodeSamples" asp-action="CSharp">C#</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="AboutMe" asp-action="Index">About Me</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-row flex-wrap me-md-auto">
                        <li class="nav-item col-6 col-sm-auto">
                            <a class="navbar-brand nav-link me-1" href="https://github.com/markrissinger/RockPaperCode">
                                <i class="bi bi-github fa-4x"></i>
                            </a>
                        </li>
                        <li class="nav-item py-2 py-lg-1 col-12 col-sm-auto">
                            <div class="vr d-none d-lg-flex h-100 mx-lg-2"></div>
                            <hr class="d-lg-none" />
                        </li>
                        <li class="nav-item dropdown me-3">
                            <a class="navbar-brand nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i id="currentThemeIcon" class=""></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" id="setThemeLight" href="#"><i class="bi bi-brightness-high small"></i>&nbsp Light </a></li>
                                <li><a class="dropdown-item" id="setThemeDark" href="#"><i class="bi bi-moon-fill small"></i>&nbsp Dark </a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <br /><br />

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
</body>
</html>